### ISSUE TITLE
Please help with new option 'mutations' )

### ISSUE THREAD

**Issue by xtrueman** [mikechris/logstash-output-clickhouse#3]
Hi!

We are trying to use our new option "mutations" but have some problems:

out config looks like:
```
...
output {
    if [fields][log_type] == 'nginx_access' {
        clickhouse {
            http_hosts => ["http://xxx:8123/"],
            table => "utr.nginx_log_buffer",
            automatic_retries => 3,
            mutations => {
                'uri' => 'uri',
                'http_host' => 'http_host',
                'http_referer' => 'http_referer',
                'http_user_agent' => 'http_user_agent',
                'method' => 'method',
                'remote_addr' => 'remote_addr',
                'request' => 'request',
                'upstream_status' => 'upstream_status',
                'upstream_response_time' => 'upstream_response_time',
                'cookie_regru_utr' => 'cookie_regru_utr',
                'request_date' => [ '@timestamp', /^(\d{4}-\d{2}-\d{2}).+/, '\1' ],
                'request_datetime' => [ '@timestamp', /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2}).+/, '\1 \2' ],
            }
        }
    }
}
...
```

We always receive the following logstash errors:
:reason=>"Expected one of #, } at line 796, column 58 (byte 26337) after output {\n    if [fields][log_type] == 'nginx_access' {\n        clickhouse {\n            http_hosts => [\"http://xxx:8123/\"]"}

We tried version with and without commas (between hash items), with regexps with or without quotes, still the same error.

May be you can help as more experienced logstash user...
Thank you! )

**Comment by funcmike** [comment]
My config is without commas between hashes, so will look like this 
```
...
        clickhouse {
            http_hosts => ["http://xxx:8123/"]
            table => "utr.nginx_log_buffer"
            automatic_retries => 3
...
```
Sorry I can't tell why syntax is failling looking at only part of it.

**Comment by gothug** [comment]
Probably should work now after some minor fixes were applied. The regex such as /^(\d{4}-\d{2}-\d{2}).+/ should be passed as string "^(\d{4}-\d{2}-\d{2}).+" in the config. Logstash config supports mostly values of string type in the config it does not understand ruby regular expression literals.
