### ISSUE TITLE
Concurrency error occurs

### ISSUE THREAD

**Issue by gothug** [mikechris/logstash-output-clickhouse#4]
Hello,

Thanks for a really useful and so good-looking plugin. Unfortunately, I'm stably receiving a concurrency error when run it.

The error looks like this:
`An unexpected error occurred! {:error=>#<ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users>, :backtrace=>["org/jruby/RubyArray.java:2486:in 'map'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:336:in 'execute!'", "/usr/share/logstash/vendor/local_gems/0626d145/logstash-output-clickhouse-0.1.0/lib/logstash/outputs/clickhouse.rb:208:in 'block in make_request'"]}`

I tried to change the code and make `client.execute!` on line 208 not in new thead but in the current thread and the error stopped to occur and everything started to work without problems.

So, I wonder if I'm only one who experiencing such a problem and why `client.execute!` is made in a separate thread whereas we specify `:async = true` flag in the `client.send()` call. To me it looks like logstash-mixin-http_client is not suited to work in multiple threads, but I may be wrong.

I run logstash with `-w 1` flag to limit the number of workers to 1.

Would be grateful for any comments and ideas. Thanks.

**Comment by funcmike** [comment]
Please submit Your fix
