### ISSUE TITLE
install use logstash-plugin with error: Plugin logstash-output-clickhouse does not exist

### ISSUE THREAD

**Issue by imweijh** [mikechris/logstash-output-clickhouse#7]
```
# bin/logstash-plugin install logstash-output-clickhouse
Validating logstash-output-clickhouse
Plugin logstash-output-clickhouse does not exist
ERROR: Installation aborted, verification failed for logstash-output-clickhouse

```

**Comment by gothug** [comment]
Hey, imweijh, this plugin is not in logstash repository.

Try these steps:

- checkout this repository
- `gem build logstash-output-clickhouse.gemspec`
- `export PATH=/usr/share/logstash/vendor/jruby/bin:$PATH` (don't remember if this step is needed, try without it at first)
- `bundle install --path /usr/share/logstash/vendor/bundle` (also, don't remember if logstash-plugin install will install bundle dependencies itself or not, so probably may be omitted, but perhaps not)
- `/usr/share/logstash/bin/logstash-plugin install logstash-output-clickhouse-0.1.0.gem`

**Comment by imweijh** [comment]
Thanks
